refresh_data:
  name: Refresh data
  description: Refresh vehicle data
  fields:
    vin:
      name: Device
      required: true
      selector:
        device:
          integration: audiconnect

execute_vehicle_action:
  name: Execute action
  description: Execute action to vehicle
  fields:
    vin:
      name: Device
      description: Set VIN code
      required: true
      selector:
        device:
          integration: audiconnect  
    action:
      required: true
      description: select service
      name: Action
      selector:
        select:
          options:
            - "lock"
            - "unlock"
            - "start_climatisation"
            - "stop_climatisation"
            - "start_charger"
            - "start_timed_charger"
            - "stop_charger"
            - "start_preheater"
            - "stop_preheater"
            - "start_window_heating"
            - "stop_window_heating"